site_name: "uima's site"
site_url: "https://uimataso.com"
author: "uima"
author_email: "me@uimataso.com"

commit_base_url: "https://github.com/uimataso/my-site-content/commit"

skip:
  - .git
  - .gitignore
  - .cspell.yaml
  - README.md
  - config.yaml

header:
  home_name: "uima's site"
  links:
    - title: blog
      url: /blog
    - title: uses
      url: /uses
    - title: blogroll
      url: /blogroll

footer:
  cc: "Â© 2025 - 2026 uima"
  links:
    - title: code of this site
      url: https://github.com/uimataso/my-site
    - title: content of this site
      url: https://github.com/uimataso/my-site-content
    - title: rss
      url: /blog/rss.xml
    - title: me@uimataso.com
      url: mailto:me@uimataso.com
